apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiflow-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiflow-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tiflow-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tiflow-operator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "tiflow-operator.serviceAccountName" . }}-manager
      containers:
        - name: manager
          securityContext:
            runAsNonRoot: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - /manager
          args:
            - --leader-elect